---
subcommands:
    add:
        # use rules of other subcommand
        use:    status
    # auth: not yet implemented
    blame:
        # aliases of subcommand - regular expression without ^ and $
        aliases:    (ann(otate)?|praise)
        # matching rules: name and regular expression
        rules:
            new:  ^\s+-\s+-\s
    # cat:
    changelist:
        aliases:    cl
        use:        status
    checkout:
        aliases:    co
        rules:
            added:          ^A
            checked_out:    ^Checked out
            conflict:       ^...C
            forced:         ^E
            restored:       ^Restored
            updated_props:  ^.U
    # cleanup:
    commit:
        aliases:    ci
        rules:
            committed:  '^Committed revision \d+'
    copy:
        aliases:    cp
        use:        status
    delete:
        aliases:    (del|remove|rm)
        use:        status
    diff:
        aliases:    di
        # use rules of other subcommand
        # when specified argument found in command line
        conditional_use:
            '--summarize':  status
        rules:
            add_file:       '^\+{3}'
            add:            '^\+{1,2}[^\+]'
            remove_file:    '^-{3}'
            remove:         '^-{1,2}[^-]'
            index:          '^(Index:|===)'
            lines:          '^[@#_]{2}'
            modified:       '^(Property changes on|Modified): '
    # export:
    help:
        aliases:    [h\?]
        rules:
            header: ^(Available subcommands|Example output|Global options|usage|Valid options):\s
    # import:
    # info:
    list:
        aliases:    ls
    # lock:
    log:
        rules:
            data:   '^r\d+\s+\|\s+\w+\s+\|\s+\d+'
            line:   '^-{10}'
    # merge:
    # mergeinfo:
    mkdir:
        use:        status
    move:
        aliases: (mv|ren(ame)?)
        use:        status
    patch:
        use:        status
    propdel:
        aliases: pd(el)?
    propedit:
        aliases: pe(dit)?
        # bypass all output processing
        interactive:    1
    propget:
        aliases: pg(et)?
    proplist:
        aliases: pl(ist)?
    propset:
        aliases: ps(et)?
    # relocate:
    # resolve:
    # resolved:
    # revert:
    status:
        aliases: st(at)?
        rules:
            # First column
            added:          ^A[^t].[^\+]
            conflict:       ^C
            deleted:        ^D..[^\+]
            existed:        ^E
            ignored:        ^I
            merged:         ^G
            modified:       ^M..[^\+]
            replaced:       ^R..[^\+]
            external:       ^X
            missing:        ^!
            kind_changed:   ^~
            # Second column - properties
            conflict_props: ^.C
            modified_props: ^.M
            updated_props:  ^.U
            # Third column - lock
            locked:         ^..L
            broken_lock:    ^..B
            # Fourth column - history
            added_with_history:     ^A[^t].\+
            deleted_with_history:   ^D..\+
            modified_with_history:  ^M..\+
            replaced_with_history:  ^R..\+
            history:                ^[^ADMR]..\+
            # Fifth column - switch
            switch:         ^....S
            # Sixth column
            locked_here:    ^.....K
            locked_other:   ^.....O
            locked_stolen:  ^.....T
            locked_broken:  ^.....B
            # Seventh column
            victim:         ^......C
            # http://svnbook.red-bean.com/en/1.7/svn.ref.svn.c.status.html
            list:           ^--- Changelist
            moved:          ^ {8}> moved
    switch:
        aliases:    sw
        use:        status
    # unlock:
    update:
        aliases:    up
        use:        status
    # upgrade:
    ALL:
        STDERR:
            rules:
                error:      '^svn: E\d+:'
                warning:    '^svn: warning: W\d+:'

# Color schema
colors:
    default:
        blame:
            new:            bold white
        checkout:
            added:          green
            conflict:       bold white on_red
            checked_out:    bold white
            forced:         cyan
            restored:       bold green
            updated_props:  black on_yellow
        commit:
            committed:      green
        diff:
            add:            green
            add_file:       bold green
            remove:         red
            remove_file:    bold red
            lines:          bold white
            index:          bold cyan
            modified:       bold yellow
        help:
            header:         bold white
        log:
            line:           bold white
            data:           bold cyan
        status:
            added:          bold green
            modified:       bold yellow
            modified_props: black on_yellow
            deleted:        bold red
            replaced:       bold cyan
            ignored:        bold black
            conflict:       bold white on_red
            missing:        black on_red
            kind_changed:   bold magenta on_blue
            list:           bold white
            locked:         black on_magenta
            moved:          cyan on_blue
            added_with_history:     bold green on_blue
            deleted_with_history:   bold red on_blue
            modified_with_history:  bold yellow on_blue
            replaced_with_history:  bold cyan on_blue
            history:                white on_blue
        STDERR:
            error:          red
            warning:        yellow
    light:
        blame:
            new:            bold black
        checkout:
            added:          green
            checked_out:    bold black
            conflict:       bold yellow on_red
            forced:         cyan
            restored:       bold green
            updated_props:  black on_yellow
        commit:
            committed:      green
        diff:
            add:            green
            add_file:       bold green
            remove:         red
            remove_file:    bold red
            lines:          bold black
            index:          bold blue
            modified:       yellow
        help:
            header:         bold black
        info:
            error:          red
            warning:        yellow
        log:
            line:           bold black
            data:           bold blue
        status:
            added:          green
            modified:       yellow
            modified_props: black on_yellow
            deleted:        red
            replaced:       cyan
            ignored:        bold black
            conflict:       bold yellow on_red
            missing:        black on_red
            kind_changed:   bold magenta on_blue
            list:           bold black
            locked:         black on_bright_magenta
            moved:          cyan on_bright_cyan
            added_with_history:     green on_bright_cyan
            deleted_with_history:   red on_bright_cyan
            modified_with_history:  yellow on_bright_cyan
            replaced_with_history:  blue on_bright_cyan
            history:                white on_bright_cyan
        STDERR:
            error:          red
            warning:        yellow
