#!/usr/bin/perl

=USAGE

    svn-st [arguments]

=head1 SEE ALSO

L<http://svnbook.red-bean.com/nightly/en/svn.ref.svn.c.status.html>

=cut

use Term::ANSIColor;

use constant COLOR => {
    '1' => {
        'A' => 'bold green',
        'M' => 'bold yellow',
        'D' => 'bold red',
        'R' => 'bold cyan',
        'I' => 'bold black',
        'C' => 'bold white on_red',
        '!' => 'black on_red',
        '~' => 'bold magenta on_blue',
    }
};

$|=1;
my $command = join ' ', 'svn st', @ARGV;

foreach ( `$command` ) {
    my $color;
    my $char = substr $_, 0, 1;
    while ( my ( $key, $value ) = each %{ COLOR->{'1'} } ) {
        $color = $value
        #,
        #last
            if $key eq $char;
    }

    print
    and next
        unless $color;

    chomp;
    print colored($_, $color), "\n";
} # foreach
